# -*- coding: utf-8 -*-
"""UHI_study6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m07mN4BA8hTiXW9MoMnWxS1iZhlMZBiz

1km Buffer Study
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

base_path = "/content/drive/MyDrive/Classic UHI"

modis_file = os.path.join(
    base_path,
    "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
)

landsat_file = os.path.join(
    base_path,
    "Classic_UHI_LST_NDVI_1km_Reference_2020_2024.csv"
)


modis = pd.read_csv(modis_file)
landsat = pd.read_csv(landsat_file)

print("MODIS columns:", modis.columns.tolist())
print("Landsat columns:", landsat.columns.tolist())


modis_pivot = modis.pivot_table(
    index=["year", "month"],
    columns="region",
    values=["mean_LST_Day_C", "mean_LST_Night_C"]
).reset_index()

modis_pivot.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in modis_pivot.columns
]

modis_pivot["Daytime_SUHI_C"] = (
    modis_pivot["mean_LST_Day_C_Urban"]
    - modis_pivot["mean_LST_Day_C_Reference_1km"]
)

modis_pivot["Nighttime_SUHI_C"] = (
    modis_pivot["mean_LST_Night_C_Urban"]
    - modis_pivot["mean_LST_Night_C_Reference_1km"]
)



landsat_urban = landsat[landsat["region"] == "Urban"].copy()



yearly_modis = modis_pivot.groupby("year").agg({
    "mean_LST_Day_C_Urban": "mean",
    "Daytime_SUHI_C": "mean",
    "mean_LST_Night_C_Urban": "mean",
    "Nighttime_SUHI_C": "mean"
}).reset_index()

yearly_ndvi = landsat_urban.groupby("year").agg({
    "mean_NDVI": "mean"
}).reset_index()

yearly_table = yearly_modis.merge(yearly_ndvi, on="year", how="left")

# ------------------------------------------------------------
# Step 6: Format like YRD table
# ------------------------------------------------------------

final_table = pd.DataFrame({
    "Parameter": [
        "Daytime LST (°C)",
        "Daytime SUHI (°C)",
        "Nighttime LST (°C)",
        "Nighttime SUHI (°C)",
        "NDVI"
    ]
})

for year in range(2020, 2025):
    row = yearly_table[yearly_table["year"] == year]
    final_table[str(year)] = [
        row["mean_LST_Day_C_Urban"].values[0],
        row["Daytime_SUHI_C"].values[0],
        row["mean_LST_Night_C_Urban"].values[0],
        row["Nighttime_SUHI_C"].values[0],
        row["mean_NDVI"].values[0]
    ]

final_table["Average"] = final_table[[str(y) for y in range(2020, 2025)]].mean(axis=1)

# Round values
final_table = final_table.round(2)

final_table

# Use final_table created in Block 1
year_cols = ["2020", "2021", "2022", "2023", "2024"]

deviation_table = final_table.copy()

for year in year_cols:
    deviation_table[year] = deviation_table[year] - deviation_table["Average"]

deviation_table = deviation_table[["Parameter"] + year_cols]

print("Deviation from 2020--2024 average:")
display(deviation_table.round(2))


n_params = len(deviation_table)

fig, axes = plt.subplots(
    nrows=2,
    ncols=3,
    figsize=(15, 8),
    sharex=True
)

axes = axes.flatten()

for i, (_, row) in enumerate(deviation_table.iterrows()):
    parameter = row["Parameter"]
    values = row[year_cols].astype(float).values

    colors = ["green" if v >= 0 else "red" for v in values]

    axes[i].bar(year_cols, values, color=colors)
    axes[i].axhline(0, color="black", linewidth=1)
    axes[i].set_title(parameter)
    axes[i].set_xlabel("Year")
    axes[i].set_ylabel("Difference from average")

for j in range(i + 1, len(axes)):
    axes[j].axis("off")

plt.suptitle(
    "Yearly LST, SUHI and NDVI deviation from 2020--2024 average",
    fontsize=14,
    y=1.02
)

plt.tight_layout()
plt.show()

base_path = "/content/drive/MyDrive/Classic UHI"

modis_file = os.path.join(
    base_path,
    "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
)

landsat_file = os.path.join(
    base_path,
    "Classic_UHI_LST_NDVI_1km_Reference_2020_2024.csv"
)



modis = pd.read_csv(modis_file)
landsat = pd.read_csv(landsat_file)

print(modis.head())
print(landsat.head())

modis_pivot = modis.pivot_table(
    index=["year", "month"],
    columns="region",
    values=["mean_LST_Day_C", "mean_LST_Night_C"]
).reset_index()

modis_pivot.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in modis_pivot.columns
]

modis_pivot["Daytime_SUHI_C"] = (
    modis_pivot["mean_LST_Day_C_Urban"]
    - modis_pivot["mean_LST_Day_C_Reference_1km"]
)

modis_pivot["Nighttime_SUHI_C"] = (
    modis_pivot["mean_LST_Night_C_Urban"]
    - modis_pivot["mean_LST_Night_C_Reference_1km"]
)



landsat_urban = landsat[landsat["region"] == "Urban"].copy()

monthly_ndvi = landsat_urban.groupby("month", as_index=False)["mean_NDVI"].mean()



monthly_modis = modis_pivot.groupby("month", as_index=False).agg({
    "mean_LST_Day_C_Urban": "mean",
    "Daytime_SUHI_C": "mean",
    "mean_LST_Night_C_Urban": "mean",
    "Nighttime_SUHI_C": "mean"
})

monthly_plot = monthly_modis.merge(monthly_ndvi, on="month", how="left")

monthly_plot

month_labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

x = monthly_plot["month"]

fig, axes = plt.subplots(2, 1, figsize=(8, 10), sharex=False)



ax1 = axes[0]

line1 = ax1.plot(
    x,
    monthly_plot["mean_LST_Day_C_Urban"],
    marker="s",
    color="magenta",
    label="Daytime LST"
)

ax1.set_ylabel("Daytime LST (°C)")
ax1.set_xticks(range(1, 13))
ax1.set_xticklabels(month_labels)
ax1.set_xlabel("Month")

ax2 = ax1.twinx()

line2 = ax2.plot(
    x,
    monthly_plot["Daytime_SUHI_C"],
    marker="^",
    color="red",
    label="Daytime SUHI"
)

ax2.set_ylabel("Daytime SUHI (°C)")

ax3 = ax1.twinx()
ax3.spines["right"].set_position(("outward", 55))

line3 = ax3.plot(
    x,
    monthly_plot["mean_NDVI"],
    marker="s",
    color="limegreen",
    label="NDVI"
)

ax3.set_ylabel("NDVI")

# Combined legend
lines = line1 + line2 + line3
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc="upper center", ncol=3, frameon=False)

ax1.text(0.03, 0.92, "a.", transform=ax1.transAxes, fontsize=12)



ax4 = axes[1]

line4 = ax4.plot(
    x,
    monthly_plot["mean_LST_Night_C_Urban"],
    marker="s",
    color="magenta",
    label="Nighttime LST"
)

ax4.set_ylabel("Nighttime LST (°C)")
ax4.set_xticks(range(1, 13))
ax4.set_xticklabels(month_labels)
ax4.set_xlabel("Month")

ax5 = ax4.twinx()

line5 = ax5.plot(
    x,
    monthly_plot["Nighttime_SUHI_C"],
    marker="v",
    color="red",
    label="Nighttime SUHI"
)

ax5.set_ylabel("Nighttime SUHI (°C)")

lines = line4 + line5
labels = [l.get_label() for l in lines]
ax4.legend(lines, labels, loc="upper center", ncol=2, frameon=False)

ax4.text(0.03, 0.92, "b.", transform=ax4.transAxes, fontsize=12)

plt.tight_layout()

output_path = os.path.join(
    base_path,
    "Monthly_LST_SUHI_NDVI_Delhi_2020_2024.png"
)

plt.savefig(output_path, dpi=300, bbox_inches="tight")
plt.show()

print("Saved figure:", output_path)

base_path = "/content/drive/MyDrive/Classic UHI"

modis_file = os.path.join(
    base_path,
    "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
)

landsat_file = os.path.join(
    base_path,
    "Classic_UHI_LST_NDVI_1km_Reference_2020_2024.csv"
)



modis = pd.read_csv(modis_file)
landsat = pd.read_csv(landsat_file)


modis = modis.drop(columns=[col for col in ["system:index", ".geo"] if col in modis.columns], errors="ignore")
landsat = landsat.drop(columns=[col for col in ["system:index", ".geo"] if col in landsat.columns], errors="ignore")


for col in ["year", "month", "mean_LST_Day_C", "mean_LST_Night_C"]:
    if col in modis.columns:
        modis[col] = pd.to_numeric(modis[col], errors="coerce")

for col in ["year", "month", "mean_NDVI"]:
    if col in landsat.columns:
        landsat[col] = pd.to_numeric(landsat[col], errors="coerce")



modis_pivot = modis.pivot_table(
    index=["year", "month"],
    columns="region",
    values=["mean_LST_Day_C", "mean_LST_Night_C"]
).reset_index()

modis_pivot.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in modis_pivot.columns
]

modis_pivot["Daytime_SUHI_C"] = (
    modis_pivot["mean_LST_Day_C_Urban"]
    - modis_pivot["mean_LST_Day_C_Reference_1km"]
)

modis_pivot["Nighttime_SUHI_C"] = (
    modis_pivot["mean_LST_Night_C_Urban"]
    - modis_pivot["mean_LST_Night_C_Reference_1km"]
)

monthly_modis = modis_pivot.groupby("month", as_index=False).agg({
    "Daytime_SUHI_C": "mean",
    "Nighttime_SUHI_C": "mean"
})



suburban_ndvi = (
    landsat[landsat["region"] == "Reference_1km"]
    .groupby("month", as_index=False)["mean_NDVI"]
    .mean()
    .rename(columns={"mean_NDVI": "Suburban_NDVI"})
)



monthly_suhi_ndvi = monthly_modis.merge(suburban_ndvi, on="month", how="left")

display(monthly_suhi_ndvi.round(3))



month_labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

fig, axes = plt.subplots(2, 1, figsize=(9, 10), sharex=False)


ax1 = axes[0]

line1 = ax1.plot(
    monthly_suhi_ndvi["month"],
    monthly_suhi_ndvi["Suburban_NDVI"],
    marker="o",
    color="blue",
    linewidth=1.8,
    markerfacecolor="white",
    label="Suburban NDVI"
)

ax1.set_ylabel("Suburban NDVI", fontsize=12)
ax1.set_xlabel("Month", fontsize=12)
ax1.set_xticks(range(1, 13))
ax1.set_xticklabels(month_labels)

ax2 = ax1.twinx()

line2 = ax2.plot(
    monthly_suhi_ndvi["month"],
    monthly_suhi_ndvi["Daytime_SUHI_C"],
    marker="^",
    color="red",
    linewidth=1.8,
    markerfacecolor="white",
    label="Daytime SUHI"
)

ax2.set_ylabel("Daytime SUHI (°C)", fontsize=12)

lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc="upper center", ncol=2, frameon=False, fontsize=11)

ax1.set_title("Monthly Suburban NDVI and Daytime SUHI using 1 km Reference, 2020--2024", fontsize=13)


ax3 = axes[1]

line3 = ax3.plot(
    monthly_suhi_ndvi["month"],
    monthly_suhi_ndvi["Suburban_NDVI"],
    marker="o",
    color="blue",
    linewidth=1.8,
    markerfacecolor="white",
    label="Suburban NDVI"
)

ax3.set_ylabel("Suburban NDVI", fontsize=12)
ax3.set_xlabel("Month", fontsize=12)
ax3.set_xticks(range(1, 13))
ax3.set_xticklabels(month_labels)

ax4 = ax3.twinx()

line4 = ax4.plot(
    monthly_suhi_ndvi["month"],
    monthly_suhi_ndvi["Nighttime_SUHI_C"],
    marker="v",
    color="red",
    linewidth=1.8,
    markerfacecolor="white",
    label="Nighttime SUHI"
)

ax4.set_ylabel("Nighttime SUHI (°C)", fontsize=12)

lines = line3 + line4
labels = [l.get_label() for l in lines]
ax3.legend(lines, labels, loc="upper center", ncol=2, frameon=False, fontsize=11)

ax3.set_title("Monthly Suburban NDVI and Nighttime SUHI using 1 km Reference, 2020--2024", fontsize=13)

plt.tight_layout()
plt.show()