# -*- coding: utf-8 -*-
"""UHI_Study7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jO3KYudufPOSiLOSBTcEOnBawCFB1t07

Air pollution Data
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import display
#Before Running the code you have to load 65 csv files on colab and MODIS and LANDSAT 5 years data

# ============================================================
# ALIPUR CPCB MISSINGNESS TEST: 5 YEARLY TABLES, 6 POLLUTANTS
# ============================================================

base_path = Path("/content")

pollutants = [
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "SO2 (µg/m³)",
    "CO (mg/m³)"
]

all_csvs = list(base_path.glob("*.csv"))
alipur_files_found = [
    f for f in all_csvs
    if "alipur" in f.name.lower() and "1h" in f.name.lower()
]

print("Alipur files found:")
for f in alipur_files_found:
    print(" -", f.name)

# Year mapping based on your confirmed CPCB filename convention:
# normal = 2024, (1) = 2023, (2) = 2022, (3) = 2021, (4) = 2020
def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

alipur_files = {
    detect_year_from_filename(f.name): f
    for f in alipur_files_found
}

print("\nYear-file mapping:")
for year in sorted(alipur_files):
    print(year, "->", alipur_files[year].name)

def missingness_for_one_year(file_path, year):
    df = pd.read_csv(file_path)


    df.columns = df.columns.str.strip()


    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")


    df = df.dropna(subset=["Timestamp"]).copy()

    df = df[df["Timestamp"].dt.year == year].copy()

    for col in pollutants:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        else:
            print(f"WARNING: {col} not found in {file_path.name}")

    full_hours = pd.date_range(
        start=f"{year}-01-01 00:00:00",
        end=f"{year}-12-31 23:00:00",
        freq="h"
    )


    df = df.drop_duplicates(subset="Timestamp", keep="first")

    df_full = df.set_index("Timestamp").reindex(full_hours)
    df_full.index.name = "Timestamp"

    rows = []

    # Monthly missingness
    for month in range(1, 13):
        month_df = df_full[df_full.index.month == month]

        row = {"Month": month}

        for col in pollutants:
            if col in df_full.columns:
                row[col] = round(month_df[col].isna().mean() * 100, 2)
            else:
                row[col] = 100.00

        rows.append(row)

    # Annual missingness
    annual_row = {"Month": "Annual"}

    for col in pollutants:
        if col in df_full.columns:
            annual_row[col] = round(df_full[col].isna().mean() * 100, 2)
        else:
            annual_row[col] = 100.00

    rows.append(annual_row)

    return pd.DataFrame(rows)

alipur_missing_tables = {}

for year in [2020, 2021, 2022, 2023, 2024]:
    print("\n" + "=" * 90)
    print(f"ALIPUR MISSINGNESS TABLE: {year}")

    if year not in alipur_files:
        print(f"ERROR: Alipur file for {year} not found.")
        continue

    table = missingness_for_one_year(alipur_files[year], year)
    alipur_missing_tables[year] = table
    display(table)

output_file = base_path / "Alipur_Missingness_2020_2024.xlsx"

with pd.ExcelWriter(output_file) as writer:
    for year, table in alipur_missing_tables.items():
        table.to_excel(writer, sheet_name=str(year), index=False)

print("\nSaved Excel file:", output_file)

# ============================================================
# STATIONWISE POLLUTANT MISSINGNESS: 13 STATIONS x 6 POLLUTANTS
# Average missingness over 2020-2024
# ============================================================

base_path = Path("/content")

pollutants = [
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "SO2 (µg/m³)",
    "CO (mg/m³)"
]

stations = {
    "TERI Gram, Gurugram": ["teri", "gram"],
    "Dr Karni Singh Shooting Range, Delhi": ["karni", "shooting"],
    "Sri Aurobindo Marg": ["aurobindo"],
    "Narela": ["narela"],
    "Najafgarh": ["najafgarh"],
    "Alipur": ["alipur"],
    "Bawana": ["bawana"],
    "Vivek Vihar, Delhi": ["vivek", "vihar"],
    "Punjabi Bagh, Delhi": ["punjabi", "bagh"],
    "Rohini, Delhi": ["rohini"],
    "Wazirpur, Delhi": ["wazirpur"],
    "ITO, New Delhi": ["ito"],
    "Mandir Marg, New Delhi": ["mandir", "marg"]
}

def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

def find_station_files(station_name, search_terms):
    all_csvs = list(base_path.glob("*.csv"))


    all_csvs = [
        f for f in all_csvs
        if "missingness" not in f.name.lower()
        and "average" not in f.name.lower()
    ]

    matched_files = []

    for f in all_csvs:
        fname = f.name.lower()

        if all(term.lower() in fname for term in search_terms) and "1h" in fname:
            matched_files.append(f)

    year_file_map = {}

    for f in matched_files:
        year = detect_year_from_filename(f.name)
        year_file_map[year] = f

    return year_file_map

def missingness_one_file(file_path, year):
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    if "Timestamp" not in df.columns:
        raise ValueError(f"Timestamp column not found in {file_path.name}")

    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    df = df.dropna(subset=["Timestamp"]).copy()


    df = df[df["Timestamp"].dt.year == year].copy()


    for col in pollutants:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    full_hours = pd.date_range(
        start=f"{year}-01-01 00:00:00",
        end=f"{year}-12-31 23:00:00",
        freq="h"
    )

    df = df.drop_duplicates(subset="Timestamp", keep="first")

    df_full = df.set_index("Timestamp").reindex(full_hours)
    df_full.index.name = "Timestamp"

    missing_percent = {}

    for col in pollutants:
        if col in df_full.columns:
            missing_percent[col] = round(df_full[col].isna().mean() * 100, 2)
        else:
            missing_percent[col] = 100.00

    return missing_percent

# ============================================================
# RUN FOR ALL 13 STATIONS
# ============================================================

stationwise_rows = []
yearwise_detail_rows = []

for station_name, search_terms in stations.items():

    print("\n" + "=" * 100)
    print("Station:", station_name)

    station_files = find_station_files(station_name, search_terms)

    print("Files detected:")
    for year in sorted(station_files):
        print(year, "->", station_files[year].name)

    yearly_missing_list = []

    for year in [2020, 2021, 2022, 2023, 2024]:

        if year not in station_files:
            print(f"WARNING: File missing for {station_name}, year {year}")

            missing_percent = {col: 100.00 for col in pollutants}

        else:
            missing_percent = missingness_one_file(station_files[year], year)

        yearly_missing_list.append(missing_percent)

        detail_row = {
            "Station": station_name,
            "Year": year
        }
        detail_row.update(missing_percent)
        yearwise_detail_rows.append(detail_row)


    station_row = {"Station": station_name}

    for col in pollutants:
        values = [year_data[col] for year_data in yearly_missing_list]
        station_row[col] = round(sum(values) / len(values), 2)

    stationwise_rows.append(station_row)

stationwise_missingness = pd.DataFrame(stationwise_rows)


stationwise_yearly_missingness = pd.DataFrame(yearwise_detail_rows)

print("\n" + "=" * 100)
print("FINAL TABLE: Average Missingness over 2020-2024")
display(stationwise_missingness)

print("\n" + "=" * 100)
print("CHECK TABLE: Year-wise Missingness")
display(stationwise_yearly_missingness)


output_avg = base_path / "Stationwise_Pollutant_Missingness_2020_2024.csv"
output_yearly = base_path / "Stationwise_Yearly_Average_Missingness_2020_2024.csv"

stationwise_missingness.to_csv(output_avg, index=False)
stationwise_yearly_missingness.to_csv(output_yearly, index=False)

print("\nSaved files:")
print(output_avg)
print(output_yearly)

# ============================================================
# TEMPORAL POLLUTANT TABLE
# Yearly average concentrations of 6 air pollutants, 2020-2024
# Output style similar to YRD Table 4
# ============================================================

base_path = Path("/content")


pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]


stations = {
    "TERI Gram, Gurugram": ["teri", "gram"],
    "Dr Karni Singh Shooting Range, Delhi": ["karni", "shooting"],
    "Sri Aurobindo Marg": ["aurobindo"],
    "Narela": ["narela"],
    "Najafgarh": ["najafgarh"],
    "Alipur": ["alipur"],
    "Bawana": ["bawana"],
    "Vivek Vihar, Delhi": ["vivek", "vihar"],
    "Punjabi Bagh, Delhi": ["punjabi", "bagh"],
    "Rohini, Delhi": ["rohini"],
    "Wazirpur, Delhi": ["wazirpur"],
    "ITO, New Delhi": ["ito"],
    "Mandir Marg, New Delhi": ["mandir", "marg"]
}

# Filename suffix rule:
# normal = 2024, (1) = 2023, (2) = 2022, (3) = 2021, (4) = 2020
def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

def find_station_files(search_terms):
    all_csvs = list(base_path.glob("*.csv"))

    # Exclude already generated output tables
    all_csvs = [
        f for f in all_csvs
        if "missingness" not in f.name.lower()
        and "average" not in f.name.lower()
        and "yearly" not in f.name.lower()
        and "table" not in f.name.lower()
    ]

    matched_files = []

    for f in all_csvs:
        fname = f.name.lower()

        if all(term.lower() in fname for term in search_terms) and "1h" in fname:
            matched_files.append(f)

    year_file_map = {}

    for f in matched_files:
        year = detect_year_from_filename(f.name)
        year_file_map[year] = f

    return year_file_map

def normalize_name(name):
    name = str(name).strip().lower()
    name = name.replace("μ", "µ")
    name = name.replace("ug", "µg")
    name = name.replace("m3", "m³")
    name = name.replace(" ", "")
    return name

def get_column_map(df):
    normalized_columns = {normalize_name(col): col for col in df.columns}

    required_map = {
        "CO (mg/m³)": ["co(mg/m³)"],
        "NO2 (µg/m³)": ["no2(µg/m³)"],
        "Ozone (µg/m³)": ["ozone(µg/m³)", "o3(µg/m³)"],
        "PM2.5 (µg/m³)": ["pm2.5(µg/m³)", "pm25(µg/m³)"],
        "PM10 (µg/m³)": ["pm10(µg/m³)"],
        "SO2 (µg/m³)": ["so2(µg/m³)"]
    }

    column_map = {}

    for clean_name, possible_names in required_map.items():
        found_col = None

        for possible in possible_names:
            possible_norm = normalize_name(possible)

            if possible_norm in normalized_columns:
                found_col = normalized_columns[possible_norm]
                break

        column_map[clean_name] = found_col

    return column_map


yearly_data = {
    2020: [],
    2021: [],
    2022: [],
    2023: [],
    2024: []
}

file_check_rows = []

for station_name, search_terms in stations.items():

    station_files = find_station_files(search_terms)

    print("\n" + "=" * 100)
    print("Station:", station_name)

    for year in [2020, 2021, 2022, 2023, 2024]:

        if year not in station_files:
            print(f"WARNING: File missing for {station_name}, {year}")
            file_check_rows.append({
                "Station": station_name,
                "Year": year,
                "File": "MISSING",
                "Rows used": 0
            })
            continue

        file_path = station_files[year]
        print(year, "->", file_path.name)

        df = pd.read_csv(file_path)
        df.columns = df.columns.str.strip()

        if "Timestamp" not in df.columns:
            print(f"WARNING: Timestamp column missing in {file_path.name}")
            file_check_rows.append({
                "Station": station_name,
                "Year": year,
                "File": file_path.name,
                "Rows used": 0
            })
            continue

        df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
        df = df.dropna(subset=["Timestamp"]).copy()
        df = df[df["Timestamp"].dt.year == year].copy()

        column_map = get_column_map(df)

        df_use = pd.DataFrame()
        df_use["Timestamp"] = df["Timestamp"]

        for clean_col in pollutants:
            original_col = column_map[clean_col]

            if original_col is None:
                print(f"WARNING: {clean_col} not found in {file_path.name}")
                df_use[clean_col] = pd.NA
            else:
                df_use[clean_col] = pd.to_numeric(df[original_col], errors="coerce")

        yearly_data[year].append(df_use)

        file_check_rows.append({
            "Station": station_name,
            "Year": year,
            "File": file_path.name,
            "Rows used": len(df_use)
        })


table_rows = []

for pollutant in pollutants:

    row = {"Air pollutants": pollutant}

    yearly_values = []

    for year in [2020, 2021, 2022, 2023, 2024]:

        if len(yearly_data[year]) == 0:
            yearly_mean = pd.NA
        else:
            year_df = pd.concat(yearly_data[year], ignore_index=True)
            yearly_mean = round(year_df[pollutant].mean(skipna=True), 2)

        row[year] = yearly_mean
        yearly_values.append(yearly_mean)

    numeric_values = [v for v in yearly_values if pd.notna(v)]
    row["Average"] = round(sum(numeric_values) / len(numeric_values), 2) if len(numeric_values) > 0 else pd.NA

    table_rows.append(row)

temporal_pollutant_table = pd.DataFrame(table_rows)

print("\n" + "=" * 100)
print("TABLE: Yearly average concentrations of air pollutants in Delhi-NCR during 2020-2024")
display(temporal_pollutant_table)

file_check_table = pd.DataFrame(file_check_rows)

print("\n" + "=" * 100)
print("FILE CHECK TABLE")
display(file_check_table)


output_table = base_path / "Table_Yearly_Average_Air_Pollutants_2020_2024.csv"
output_check = base_path / "File_Check_Air_Pollutants_2020_2024.csv"

temporal_pollutant_table.to_csv(output_table, index=False)
file_check_table.to_csv(output_check, index=False)

print("\nSaved files:")
print(output_table)
print(output_check)

"""SUHI + Pollutant Analysis

"""

# ------------------------------------------------------------
# Block 3: One-image pollutant deviation plots
# Positive/negative comparison from 2020--2024 average
# ------------------------------------------------------------

import matplotlib.pyplot as plt
import numpy as np

year_cols = [2020, 2021, 2022, 2023, 2024]

pollutant_deviation_table = temporal_pollutant_table.copy()

for year in year_cols:
    pollutant_deviation_table[year] = (
        pollutant_deviation_table[year] - pollutant_deviation_table["Average"]
    )

pollutant_deviation_table = pollutant_deviation_table[["Air pollutants"] + year_cols]

print("Pollutant deviation from 2020--2024 average:")
display(pollutant_deviation_table.round(2))

n_pollutants = len(pollutant_deviation_table)

fig, axes = plt.subplots(
    nrows=2,
    ncols=3,
    figsize=(15, 8),
    sharex=True
)

axes = axes.flatten()

for i, (_, row) in enumerate(pollutant_deviation_table.iterrows()):
    pollutant = row["Air pollutants"]
    values = row[year_cols].astype(float).values

    colors = ["green" if v >= 0 else "red" for v in values]

    axes[i].bar([str(y) for y in year_cols], values, color=colors)
    axes[i].axhline(0, color="black", linewidth=1)
    axes[i].set_title(pollutant)
    axes[i].set_xlabel("Year")
    axes[i].set_ylabel("Difference from average")

for j in range(i + 1, len(axes)):
    axes[j].axis("off")

plt.suptitle(
    "Yearly pollutant deviation from 2020--2024 average",
    fontsize=14,
    y=1.02
)

plt.tight_layout()
plt.show()

# ============================================================
# MONTHLY AIR POLLUTANT PLOTS FOR NCT DELHI
# Years: 2023 and 2024
# All 13 stations together
# Save:
#   1) Monthly_Air_Pollutants_NCT_Delhi_2023.png
#   2) Monthly_Air_Pollutants_NCT_Delhi_2024.png
# Also save monthly tables as CSV for checking
# ============================================================

# ---------- paths ----------
base_path = Path("/content")
drive_output = Path("/content/drive/MyDrive/Classic UHI")
output_path = drive_output if drive_output.exists() else base_path
print("Output path:", output_path)

# ---------- pollutants ----------
pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

# ---------- final 13 stations ----------
stations = {
    "TERI Gram, Gurugram": ["teri", "gram"],
    "Dr Karni Singh Shooting Range, Delhi": ["karni", "shooting"],
    "Sri Aurobindo Marg": ["aurobindo"],
    "Narela": ["narela"],
    "Najafgarh": ["najafgarh"],
    "Alipur": ["alipur"],
    "Bawana": ["bawana"],
    "Vivek Vihar, Delhi": ["vivek", "vihar"],
    "Punjabi Bagh, Delhi": ["punjabi", "bagh"],
    "Rohini, Delhi": ["rohini"],
    "Wazirpur, Delhi": ["wazirpur"],
    "ITO, New Delhi": ["ito"],
    "Mandir Marg, New Delhi": ["mandir", "marg"]
}


def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

def find_station_files(search_terms):
    all_csvs = list(base_path.glob("*.csv"))


    all_csvs = [
        f for f in all_csvs
        if "missingness" not in f.name.lower()
        and "average" not in f.name.lower()
        and "yearly" not in f.name.lower()
        and "monthly_air_pollutants" not in f.name.lower()
        and "table_" not in f.name.lower()
        and "file_check" not in f.name.lower()
    ]

    matched_files = []
    for f in all_csvs:
        fname = f.name.lower()
        if all(term.lower() in fname for term in search_terms) and "1h" in fname:
            matched_files.append(f)

    year_file_map = {}
    for f in matched_files:
        year = detect_year_from_filename(f.name)
        year_file_map[year] = f

    return year_file_map

def normalize_name(name):
    name = str(name).strip().lower()
    name = name.replace("μ", "µ")
    name = name.replace("ug", "µg")
    name = name.replace("m3", "m³")
    name = name.replace(" ", "")
    return name

def get_column_map(df):
    normalized_columns = {normalize_name(col): col for col in df.columns}

    required_map = {
        "CO (mg/m³)": ["co(mg/m³)"],
        "NO2 (µg/m³)": ["no2(µg/m³)"],
        "Ozone (µg/m³)": ["ozone(µg/m³)", "o3(µg/m³)"],
        "PM2.5 (µg/m³)": ["pm2.5(µg/m³)", "pm25(µg/m³)"],
        "PM10 (µg/m³)": ["pm10(µg/m³)"],
        "SO2 (µg/m³)": ["so2(µg/m³)"]
    }

    column_map = {}
    for clean_name, possible_names in required_map.items():
        found_col = None
        for possible in possible_names:
            possible_norm = normalize_name(possible)
            if possible_norm in normalized_columns:
                found_col = normalized_columns[possible_norm]
                break
        column_map[clean_name] = found_col

    return column_map

def get_station_monthly_means(file_path, year):
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    if "Timestamp" not in df.columns:
        raise ValueError(f"Timestamp column not found in {file_path.name}")

    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    df = df.dropna(subset=["Timestamp"]).copy()
    df = df[df["Timestamp"].dt.year == year].copy()

    column_map = get_column_map(df)

    df_use = pd.DataFrame()
    df_use["Timestamp"] = df["Timestamp"]

    for clean_col in pollutants:
        original_col = column_map[clean_col]
        if original_col is None:
            print(f"WARNING: {clean_col} not found in {file_path.name}")
            df_use[clean_col] = pd.NA
        else:
            df_use[clean_col] = pd.to_numeric(df[original_col], errors="coerce")

    df_use["Month"] = df_use["Timestamp"].dt.month

    monthly_means = (
        df_use.groupby("Month")[pollutants]
        .mean()
        .round(2)
        .reset_index()
    )

    return monthly_means

def month_labels():
    return ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

def make_yrd_style_plot(monthly_df, year, save_path):
    months = monthly_df["Month"].tolist()
    labels = month_labels()

    fig, axes = plt.subplots(2, 1, figsize=(9, 10))

    # ---------------- panel a: NO2, O3, CO ----------------
    ax1 = axes[0]
    ax1b = ax1.twinx()
    ax1c = ax1.twinx()
    ax1c.spines["right"].set_position(("axes", 1.12))

    l1 = ax1.plot(months, monthly_df["NO2 (µg/m³)"], marker="^", label="NO$_2$")
    l2 = ax1b.plot(months, monthly_df["Ozone (µg/m³)"], marker="s", label="O$_3$")
    l3 = ax1c.plot(months, monthly_df["CO (mg/m³)"], marker="o", label="CO")

    ax1.set_xlim(1, 12)
    ax1.set_xticks(months)
    ax1.set_xticklabels(labels)
    ax1.set_xlabel("Month")
    ax1.set_ylabel("NO$_2$ (µg/m$^3$)")
    ax1b.set_ylabel("O$_3$ (µg/m$^3$)")
    ax1c.set_ylabel("CO (mg/m$^3$)")
    ax1.set_title(f"a. Monthly average concentrations of NO$_2$, O$_3$ and CO in NCT Delhi ({year})", loc="left", fontsize=11)

    lines = l1 + l2 + l3
    labels_combined = [line.get_label() for line in lines]
    ax1.legend(lines, labels_combined, loc="upper center", ncol=3, frameon=False)

    # ---------------- panel b: PM2.5, PM10, SO2 ----------------
    ax2 = axes[1]
    ax2b = ax2.twinx()
    ax2c = ax2.twinx()
    ax2c.spines["right"].set_position(("axes", 1.12))

    l4 = ax2.plot(months, monthly_df["PM2.5 (µg/m³)"], marker="^", label="PM$_{2.5}$")
    l5 = ax2b.plot(months, monthly_df["PM10 (µg/m³)"], marker="v", label="PM$_{10}$")
    l6 = ax2c.plot(months, monthly_df["SO2 (µg/m³)"], marker="^", linestyle="--", label="SO$_2$")

    ax2.set_xlim(1, 12)
    ax2.set_xticks(months)
    ax2.set_xticklabels(labels)
    ax2.set_xlabel("Month")
    ax2.set_ylabel("PM$_{2.5}$ (µg/m$^3$)")
    ax2b.set_ylabel("PM$_{10}$ (µg/m$^3$)")
    ax2c.set_ylabel("SO$_2$ (µg/m$^3$)")
    ax2.set_title(f"b. Monthly average concentrations of PM$_{{2.5}}$, PM$_{{10}}$ and SO$_2$ in NCT Delhi ({year})", loc="left", fontsize=11)

    lines2 = l4 + l5 + l6
    labels_combined2 = [line.get_label() for line in lines2]
    ax2.legend(lines2, labels_combined2, loc="upper center", ncol=3, frameon=False)

    fig.suptitle(f"Monthly average concentrations of air pollutants in NCT Delhi in {year}", fontsize=13, y=0.98)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()



all_monthly_outputs = {}

for target_year in [2023, 2024]:
    print("\n" + "=" * 110)
    print("PROCESSING YEAR:", target_year)

    station_monthly_list = []
    file_check_rows = []

    for station_name, search_terms in stations.items():
        station_files = find_station_files(search_terms)

        if target_year not in station_files:
            print(f"WARNING: File missing for {station_name}, {target_year}")
            file_check_rows.append({
                "Station": station_name,
                "Year": target_year,
                "File": "MISSING"
            })
            continue

        file_path = station_files[target_year]
        print(station_name, "->", file_path.name)

        monthly_means = get_station_monthly_means(file_path, target_year)
        monthly_means["Station"] = station_name
        station_monthly_list.append(monthly_means)

        file_check_rows.append({
            "Station": station_name,
            "Year": target_year,
            "File": file_path.name
        })

    if len(station_monthly_list) == 0:
        print(f"ERROR: No station files found for {target_year}")
        continue

    # Equal-weight monthly average across stations
    all_station_monthly = pd.concat(station_monthly_list, ignore_index=True)

    monthly_nct = (
        all_station_monthly.groupby("Month")[pollutants]
        .mean()
        .round(2)
        .reset_index()
    )

    all_monthly_outputs[target_year] = monthly_nct

    print("\nMONTHLY TABLE FOR", target_year)
    display(monthly_nct)

    # Save monthly table
    table_save = output_path / f"Monthly_Average_Air_Pollutants_NCT_Delhi_{target_year}.csv"
    monthly_nct.to_csv(table_save, index=False)

    # Save file-check table
    file_check_table = pd.DataFrame(file_check_rows)
    check_save = output_path / f"File_Check_Monthly_Air_Pollutants_{target_year}.csv"
    file_check_table.to_csv(check_save, index=False)

    # Plot and save figure
    fig_save = output_path / f"Monthly_Air_Pollutants_NCT_Delhi_{target_year}.png"
    make_yrd_style_plot(monthly_nct, target_year, fig_save)

    print("Saved monthly table:", table_save)
    print("Saved file check:", check_save)
    print("Saved figure:", fig_save)

print("\nDone.")

# ============================================================
# Average across 13 stations
# For later merge with nighttime SUHI
# ============================================================

base_path = Path("/content")
target_year = 2023

pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

stations = {
    "TERI Gram, Gurugram": ["teri", "gram"],
    "Dr Karni Singh Shooting Range, Delhi": ["karni", "shooting"],
    "Sri Aurobindo Marg": ["aurobindo"],
    "Narela": ["narela"],
    "Najafgarh": ["najafgarh"],
    "Alipur": ["alipur"],
    "Bawana": ["bawana"],
    "Vivek Vihar, Delhi": ["vivek", "vihar"],
    "Punjabi Bagh, Delhi": ["punjabi", "bagh"],
    "Rohini, Delhi": ["rohini"],
    "Wazirpur, Delhi": ["wazirpur"],
    "ITO, New Delhi": ["ito"],
    "Mandir Marg, New Delhi": ["mandir", "marg"]
}

def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

def find_station_files(search_terms):
    all_csvs = list(base_path.glob("*.csv"))

    # Avoid generated output files
    all_csvs = [
        f for f in all_csvs
        if "missingness" not in f.name.lower()
        and "average" not in f.name.lower()
        and "yearly" not in f.name.lower()
        and "monthly_air_pollutants" not in f.name.lower()
        and "table_" not in f.name.lower()
        and "file_check" not in f.name.lower()
        and "merged" not in f.name.lower()
        and "correlation" not in f.name.lower()
    ]

    matched_files = []

    for f in all_csvs:
        fname = f.name.lower()

        if all(term.lower() in fname for term in search_terms) and "1h" in fname:
            matched_files.append(f)

    year_file_map = {}

    for f in matched_files:
        year = detect_year_from_filename(f.name)
        year_file_map[year] = f

    return year_file_map

def normalize_name(name):
    name = str(name).strip().lower()
    name = name.replace("μ", "µ")
    name = name.replace("ug", "µg")
    name = name.replace("m3", "m³")
    name = name.replace(" ", "")
    return name

def get_column_map(df):
    normalized_columns = {normalize_name(col): col for col in df.columns}

    required_map = {
        "CO (mg/m³)": ["co(mg/m³)"],
        "NO2 (µg/m³)": ["no2(µg/m³)"],
        "Ozone (µg/m³)": ["ozone(µg/m³)", "o3(µg/m³)"],
        "PM2.5 (µg/m³)": ["pm2.5(µg/m³)", "pm25(µg/m³)"],
        "PM10 (µg/m³)": ["pm10(µg/m³)"],
        "SO2 (µg/m³)": ["so2(µg/m³)"]
    }

    column_map = {}

    for clean_name, possible_names in required_map.items():
        found_col = None

        for possible in possible_names:
            possible_norm = normalize_name(possible)

            if possible_norm in normalized_columns:
                found_col = normalized_columns[possible_norm]
                break

        column_map[clean_name] = found_col

    return column_map

def get_station_monthly_means(file_path, year, station_name):
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    if "Timestamp" not in df.columns:
        raise ValueError(f"Timestamp column not found in {file_path.name}")

    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    df = df.dropna(subset=["Timestamp"]).copy()
    df = df[df["Timestamp"].dt.year == year].copy()

    column_map = get_column_map(df)

    df_use = pd.DataFrame()
    df_use["Timestamp"] = df["Timestamp"]

    for clean_col in pollutants:
        original_col = column_map[clean_col]

        if original_col is None:
            print(f"WARNING: {clean_col} not found in {file_path.name}")
            df_use[clean_col] = pd.NA
        else:
            df_use[clean_col] = pd.to_numeric(df[original_col], errors="coerce")

    df_use["Month"] = df_use["Timestamp"].dt.month
    df_use["Station"] = station_name

    monthly_means = (
        df_use
        .groupby(["Station", "Month"])[pollutants]
        .mean()
        .round(2)
        .reset_index()
    )

    return monthly_means, len(df_use)



station_monthly_list = []
file_check_rows = []

print("=" * 100)
print("PROCESSING MONTHLY AIR POLLUTION DATA FOR:", target_year)

for station_name, search_terms in stations.items():

    station_files = find_station_files(search_terms)

    if target_year not in station_files:
        print(f"WARNING: File missing for {station_name}, {target_year}")

        file_check_rows.append({
            "Station": station_name,
            "Year": target_year,
            "File": "MISSING",
            "Rows used": 0
        })

        continue

    file_path = station_files[target_year]

    print(station_name, "->", file_path.name)

    monthly_means, rows_used = get_station_monthly_means(
        file_path=file_path,
        year=target_year,
        station_name=station_name
    )

    station_monthly_list.append(monthly_means)

    file_check_rows.append({
        "Station": station_name,
        "Year": target_year,
        "File": file_path.name,
        "Rows used": rows_used
    })

# Station-wise monthly table
stationwise_monthly_2023 = pd.concat(station_monthly_list, ignore_index=True)

monthly_pollution_2023 = (
    stationwise_monthly_2023
    .groupby("Month")[pollutants]
    .mean()
    .round(2)
    .reset_index()
)

monthly_pollution_2023.insert(0, "Year", target_year)

file_check_2023 = pd.DataFrame(file_check_rows)

print("\n" + "=" * 100)
print("FINAL 2023 MONTHLY POLLUTION TABLE: Average across 13 stations")
display(monthly_pollution_2023)

print("\n" + "=" * 100)
print("FILE CHECK TABLE")
display(file_check_2023)

print("\n" + "=" * 100)
print("STATION-WISE MONTHLY TABLE FOR CHECKING")
display(stationwise_monthly_2023)

# Save outputs
output_monthly = base_path / "Monthly_Pollution_Average_13Stations_2023.csv"
output_stationwise = base_path / "Stationwise_Monthly_Pollution_2023.csv"
output_check = base_path / "File_Check_Pollution_2023.csv"

monthly_pollution_2023.to_csv(output_monthly, index=False)
stationwise_monthly_2023.to_csv(output_stationwise, index=False)
file_check_2023.to_csv(output_check, index=False)

print("\nSaved files:")
print(output_monthly)
print(output_stationwise)
print(output_check)

# ============================================================
# Average across 13 stations
# For later merge with nighttime SUHI
# ============================================================

base_path = Path("/content")
target_year = 2024

pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

stations = {
    "TERI Gram, Gurugram": ["teri", "gram"],
    "Dr Karni Singh Shooting Range, Delhi": ["karni", "shooting"],
    "Sri Aurobindo Marg": ["aurobindo"],
    "Narela": ["narela"],
    "Najafgarh": ["najafgarh"],
    "Alipur": ["alipur"],
    "Bawana": ["bawana"],
    "Vivek Vihar, Delhi": ["vivek", "vihar"],
    "Punjabi Bagh, Delhi": ["punjabi", "bagh"],
    "Rohini, Delhi": ["rohini"],
    "Wazirpur, Delhi": ["wazirpur"],
    "ITO, New Delhi": ["ito"],
    "Mandir Marg, New Delhi": ["mandir", "marg"]
}

def detect_year_from_filename(filename):
    if "(4)" in filename:
        return 2020
    elif "(3)" in filename:
        return 2021
    elif "(2)" in filename:
        return 2022
    elif "(1)" in filename:
        return 2023
    else:
        return 2024

def find_station_files(search_terms):
    all_csvs = list(base_path.glob("*.csv"))

    all_csvs = [
        f for f in all_csvs
        if "missingness" not in f.name.lower()
        and "average" not in f.name.lower()
        and "yearly" not in f.name.lower()
        and "monthly_air_pollutants" not in f.name.lower()
        and "table_" not in f.name.lower()
        and "file_check" not in f.name.lower()
        and "merged" not in f.name.lower()
        and "correlation" not in f.name.lower()
    ]

    matched_files = []

    for f in all_csvs:
        fname = f.name.lower()

        if all(term.lower() in fname for term in search_terms) and "1h" in fname:
            matched_files.append(f)

    year_file_map = {}

    for f in matched_files:
        year = detect_year_from_filename(f.name)
        year_file_map[year] = f

    return year_file_map

def normalize_name(name):
    name = str(name).strip().lower()
    name = name.replace("μ", "µ")
    name = name.replace("ug", "µg")
    name = name.replace("m3", "m³")
    name = name.replace(" ", "")
    return name

def get_column_map(df):
    normalized_columns = {normalize_name(col): col for col in df.columns}

    required_map = {
        "CO (mg/m³)": ["co(mg/m³)"],
        "NO2 (µg/m³)": ["no2(µg/m³)"],
        "Ozone (µg/m³)": ["ozone(µg/m³)", "o3(µg/m³)"],
        "PM2.5 (µg/m³)": ["pm2.5(µg/m³)", "pm25(µg/m³)"],
        "PM10 (µg/m³)": ["pm10(µg/m³)"],
        "SO2 (µg/m³)": ["so2(µg/m³)"]
    }

    column_map = {}

    for clean_name, possible_names in required_map.items():
        found_col = None

        for possible in possible_names:
            possible_norm = normalize_name(possible)

            if possible_norm in normalized_columns:
                found_col = normalized_columns[possible_norm]
                break

        column_map[clean_name] = found_col

    return column_map

def get_station_monthly_means(file_path, year, station_name):
    df = pd.read_csv(file_path)
    df.columns = df.columns.str.strip()

    if "Timestamp" not in df.columns:
        raise ValueError(f"Timestamp column not found in {file_path.name}")

    df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")
    df = df.dropna(subset=["Timestamp"]).copy()
    df = df[df["Timestamp"].dt.year == year].copy()

    column_map = get_column_map(df)

    df_use = pd.DataFrame()
    df_use["Timestamp"] = df["Timestamp"]

    for clean_col in pollutants:
        original_col = column_map[clean_col]

        if original_col is None:
            print(f"WARNING: {clean_col} not found in {file_path.name}")
            df_use[clean_col] = pd.NA
        else:
            df_use[clean_col] = pd.to_numeric(df[original_col], errors="coerce")

    df_use["Month"] = df_use["Timestamp"].dt.month
    df_use["Station"] = station_name

    monthly_means = (
        df_use
        .groupby(["Station", "Month"])[pollutants]
        .mean()
        .round(2)
        .reset_index()
    )

    return monthly_means, len(df_use)


station_monthly_list = []
file_check_rows = []

print("=" * 100)
print("PROCESSING MONTHLY AIR POLLUTION DATA FOR:", target_year)

for station_name, search_terms in stations.items():

    station_files = find_station_files(search_terms)

    if target_year not in station_files:
        print(f"WARNING: File missing for {station_name}, {target_year}")

        file_check_rows.append({
            "Station": station_name,
            "Year": target_year,
            "File": "MISSING",
            "Rows used": 0
        })

        continue

    file_path = station_files[target_year]

    print(station_name, "->", file_path.name)

    monthly_means, rows_used = get_station_monthly_means(
        file_path=file_path,
        year=target_year,
        station_name=station_name
    )

    station_monthly_list.append(monthly_means)

    file_check_rows.append({
        "Station": station_name,
        "Year": target_year,
        "File": file_path.name,
        "Rows used": rows_used
    })

stationwise_monthly_2024 = pd.concat(station_monthly_list, ignore_index=True)

monthly_pollution_2024 = (
    stationwise_monthly_2024
    .groupby("Month")[pollutants]
    .mean()
    .round(2)
    .reset_index()
)

monthly_pollution_2024.insert(0, "Year", target_year)

file_check_2024 = pd.DataFrame(file_check_rows)

print("\n" + "=" * 100)
print("FINAL 2024 MONTHLY POLLUTION TABLE: Average across 13 stations")
display(monthly_pollution_2024)

print("\n" + "=" * 100)
print("FILE CHECK TABLE")
display(file_check_2024)

print("\n" + "=" * 100)
print("STATION-WISE MONTHLY TABLE FOR CHECKING")
display(stationwise_monthly_2024)

# Save outputs
output_monthly = base_path / "Monthly_Pollution_Average_13Stations_2024.csv"
output_stationwise = base_path / "Stationwise_Monthly_Pollution_2024.csv"
output_check = base_path / "File_Check_Pollution_2024.csv"

monthly_pollution_2024.to_csv(output_monthly, index=False)
stationwise_monthly_2024.to_csv(output_stationwise, index=False)
file_check_2024.to_csv(output_check, index=False)

print("\nSaved files:")
print(output_monthly)
print(output_stationwise)
print(output_check)

# ============================================================
# MODIS LST + SUHI + AIR POLLUTANTS
# ============================================================

base_path = Path("/content")
drive_path = Path("/content/drive/MyDrive/Classic UHI")

target_year = 2023

modis_file = drive_path / "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
pollution_file = base_path / "Monthly_Pollution_Average_13Stations_2023.csv"



modis_df = pd.read_csv(modis_file)
modis_df.columns = modis_df.columns.str.strip()

print("MODIS columns:")
print(list(modis_df.columns))

modis_df = modis_df[
    [
        "year",
        "month",
        "region",
        "mean_LST_Day_C",
        "mean_LST_Night_C"
    ]
].copy()


modis_2023 = modis_df[modis_df["year"] == target_year].copy()



modis_pivot = modis_2023.pivot_table(
    index=["year", "month"],
    columns="region",
    values=["mean_LST_Day_C", "mean_LST_Night_C"],
    aggfunc="mean"
)

# Flatten column names
modis_pivot.columns = [
    f"{value}_{region}" for value, region in modis_pivot.columns
]

modis_pivot = modis_pivot.reset_index()



modis_pivot["Daytime LST (°C)"] = modis_pivot["mean_LST_Day_C_Urban"]
modis_pivot["Nighttime LST (°C)"] = modis_pivot["mean_LST_Night_C_Urban"]

modis_pivot["Daytime Reference LST (°C)"] = modis_pivot["mean_LST_Day_C_Reference_1km"]
modis_pivot["Nighttime Reference LST (°C)"] = modis_pivot["mean_LST_Night_C_Reference_1km"]

modis_pivot["Daytime SUHI (°C)"] = (
    modis_pivot["Daytime LST (°C)"] -
    modis_pivot["Daytime Reference LST (°C)"]
)

modis_pivot["Nighttime SUHI (°C)"] = (
    modis_pivot["Nighttime LST (°C)"] -
    modis_pivot["Nighttime Reference LST (°C)"]
)

suhi_2023 = modis_pivot[
    [
        "year",
        "month",
        "Daytime LST (°C)",
        "Daytime Reference LST (°C)",
        "Daytime SUHI (°C)",
        "Nighttime LST (°C)",
        "Nighttime Reference LST (°C)",
        "Nighttime SUHI (°C)"
    ]
].copy()

suhi_2023 = suhi_2023.rename(columns={
    "year": "Year",
    "month": "Month"
})

suhi_2023 = suhi_2023.round(2)

print("\n2023 MODIS LST and SUHI table:")
display(suhi_2023)



monthly_pollution_2023 = pd.read_csv(pollution_file)

monthly_pollution_2023["Year"] = monthly_pollution_2023["Year"].astype(int)
monthly_pollution_2023["Month"] = monthly_pollution_2023["Month"].astype(int)

print("\n2023 monthly pollution table:")
display(monthly_pollution_2023)



merged_2023 = pd.merge(
    suhi_2023,
    monthly_pollution_2023,
    on=["Year", "Month"],
    how="inner"
)

merged_2023 = merged_2023.round(2)

print("\nFINAL MERGED 2023 TABLE: LST + SUHI + POLLUTANTS")
display(merged_2023)



output_file = base_path / "Merged_LST_SUHI_Pollution_2023.csv"
merged_2023.to_csv(output_file, index=False)

print("\nSaved:", output_file)

# ============================================================
# Triple-scale plots: Nighttime SUHI + two pollutants
# ============================================================

base_path = Path("/content")

merged_file = base_path / "Merged_LST_SUHI_Pollution_2023.csv"

df = pd.read_csv(merged_file)


month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

df["Month_Name"] = df["Month"].map(month_names)

display(df)



def plot_triple_scale(df, pollutant_1, pollutant_2, title, output_name):

    fig, ax1 = plt.subplots(figsize=(10, 5))


    ax1.plot(
        df["Month_Name"],
        df["Nighttime SUHI (°C)"],
        marker="o",
        linewidth=2,
        label="Nighttime SUHI"
    )

    ax1.set_xlabel("Month")
    ax1.set_ylabel("Nighttime SUHI (°C)")
    ax1.tick_params(axis="x", rotation=45)


    ax2 = ax1.twinx()

    ax2.plot(
        df["Month_Name"],
        df[pollutant_1],
        marker="s",
        linewidth=2,
        linestyle="--",
        label=pollutant_1
    )

    ax2.set_ylabel(pollutant_1)

    ax3 = ax1.twinx()

    ax3.spines["right"].set_position(("outward", 60))

    ax3.plot(
        df["Month_Name"],
        df[pollutant_2],
        marker="^",
        linewidth=2,
        linestyle=":",
        label=pollutant_2
    )

    ax3.set_ylabel(pollutant_2)

    # Combined legend
    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    lines_3, labels_3 = ax3.get_legend_handles_labels()

    ax1.legend(
        lines_1 + lines_2 + lines_3,
        labels_1 + labels_2 + labels_3,
        loc="upper left",
        fontsize=9
    )

    ax1.set_title(title)
    ax1.grid(True, alpha=0.3)

    plt.tight_layout()

    output_path = base_path / output_name
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

    print("Saved:", output_path)


# ------------------------------------------------------------
# Plot 1: Nighttime SUHI with particulate pollutants
# ------------------------------------------------------------

plot_triple_scale(
    df=df,
    pollutant_1="PM2.5 (µg/m³)",
    pollutant_2="PM10 (µg/m³)",
    title="Monthly Nighttime SUHI with PM2.5 and PM10 during 2023",
    output_name="Nighttime_SUHI_PM25_PM10_2023.png"
)


# ------------------------------------------------------------
# Plot 2: Nighttime SUHI with combustion-related gaseous pollutants
# ------------------------------------------------------------

plot_triple_scale(
    df=df,
    pollutant_1="NO2 (µg/m³)",
    pollutant_2="CO (mg/m³)",
    title="Monthly Nighttime SUHI with NO2 and CO during 2023",
    output_name="Nighttime_SUHI_NO2_CO_2023.png"
)


# ------------------------------------------------------------
# Plot 3: Nighttime SUHI with Ozone and SO2
# ------------------------------------------------------------

plot_triple_scale(
    df=df,
    pollutant_1="Ozone (µg/m³)",
    pollutant_2="SO2 (µg/m³)",
    title="Monthly Nighttime SUHI with Ozone and SO2 during 2023",
    output_name="Nighttime_SUHI_Ozone_SO2_2023.png"
)

# ============================================================
# Triple-scale plots: Daytime SUHI + two pollutants
# ============================================================

base_path = Path("/content")

merged_file = base_path / "Merged_LST_SUHI_Pollution_2023.csv"

df = pd.read_csv(merged_file)

# Month labels
month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

df["Month_Name"] = df["Month"].map(month_names)

display(df)


def plot_triple_scale_daytime(df, pollutant_1, pollutant_2, title, output_name):

    fig, ax1 = plt.subplots(figsize=(10, 5))


    ax1.plot(
        df["Month_Name"],
        df["Daytime SUHI (°C)"],
        marker="o",
        linewidth=2,
        label="Daytime SUHI"
    )

    ax1.set_xlabel("Month")
    ax1.set_ylabel("Daytime SUHI (°C)")
    ax1.tick_params(axis="x", rotation=45)


    ax2 = ax1.twinx()

    ax2.plot(
        df["Month_Name"],
        df[pollutant_1],
        marker="s",
        linewidth=2,
        linestyle="--",
        label=pollutant_1
    )

    ax2.set_ylabel(pollutant_1)


    ax3 = ax1.twinx()

    ax3.spines["right"].set_position(("outward", 60))

    ax3.plot(
        df["Month_Name"],
        df[pollutant_2],
        marker="^",
        linewidth=2,
        linestyle=":",
        label=pollutant_2
    )

    ax3.set_ylabel(pollutant_2)

    # Combined legend
    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    lines_3, labels_3 = ax3.get_legend_handles_labels()

    ax1.legend(
        lines_1 + lines_2 + lines_3,
        labels_1 + labels_2 + labels_3,
        loc="upper left",
        fontsize=9
    )

    ax1.set_title(title)
    ax1.grid(True, alpha=0.3)

    plt.tight_layout()

    output_path = base_path / output_name
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

    print("Saved:", output_path)


# ------------------------------------------------------------
# Plot 1: Daytime SUHI with particulate pollutants
# ------------------------------------------------------------

plot_triple_scale_daytime(
    df=df,
    pollutant_1="PM2.5 (µg/m³)",
    pollutant_2="PM10 (µg/m³)",
    title="Monthly Daytime SUHI with PM2.5 and PM10 during 2023",
    output_name="Daytime_SUHI_PM25_PM10_2023.png"
)


# ------------------------------------------------------------
# Plot 2: Daytime SUHI with combustion-related gaseous pollutants
# ------------------------------------------------------------

plot_triple_scale_daytime(
    df=df,
    pollutant_1="NO2 (µg/m³)",
    pollutant_2="CO (mg/m³)",
    title="Monthly Daytime SUHI with NO2 and CO during 2023",
    output_name="Daytime_SUHI_NO2_CO_2023.png"
)


# ------------------------------------------------------------
# Plot 3: Daytime SUHI with Ozone and SO2
# ------------------------------------------------------------

plot_triple_scale_daytime(
    df=df,
    pollutant_1="Ozone (µg/m³)",
    pollutant_2="SO2 (µg/m³)",
    title="Monthly Daytime SUHI with Ozone and SO2 during 2023",
    output_name="Daytime_SUHI_Ozone_SO2_2023.png"
)

# ============================================================
# Main focus: Nighttime SUHI
# Supporting: Daytime SUHI
# ============================================================

base_path = Path("/content")

merged_file = base_path / "Merged_LST_SUHI_Pollution_2023.csv"

df = pd.read_csv(merged_file)

pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

suhi_columns = [
    "Nighttime SUHI (°C)",
    "Daytime SUHI (°C)"
]

correlation_rows = []

for pollutant in pollutants:

    row = {
        "Pollutant": pollutant
    }

    for suhi_col in suhi_columns:

        temp = df[[suhi_col, pollutant]].dropna()

        if len(temp) >= 3:
            r_value, p_value = pearsonr(temp[suhi_col], temp[pollutant])
        else:
            r_value, p_value = None, None

        if suhi_col == "Nighttime SUHI (°C)":
            row["Nighttime SUHI r"] = r_value
            row["Nighttime SUHI p-value"] = p_value

        elif suhi_col == "Daytime SUHI (°C)":
            row["Daytime SUHI r"] = r_value
            row["Daytime SUHI p-value"] = p_value

    correlation_rows.append(row)

correlation_2023 = pd.DataFrame(correlation_rows)

correlation_2023 = correlation_2023[
    [
        "Pollutant",
        "Nighttime SUHI r",
        "Nighttime SUHI p-value",
        "Daytime SUHI r",
        "Daytime SUHI p-value"
    ]
]

correlation_2023 = correlation_2023.round(3)

print("2023 SUHI vs pollutant correlation table")
display(correlation_2023)


output_file = base_path / "SUHI_Pollutant_Correlation_2023.csv"
correlation_2023.to_csv(output_file, index=False)

print("\nSaved:", output_file)

# ============================================================
# 1. Calculate 2024 SUHI from MODIS file
# 2. Merge with 2024 monthly pollutants
# 3. Plot Nighttime SUHI with pollutants using triple-scale plots
# ============================================================

base_path = Path("/content")
drive_path = Path("/content/drive/MyDrive/Classic UHI")

target_year = 2024

modis_file = drive_path / "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
pollution_file = base_path / "Monthly_Pollution_Average_13Stations_2024.csv"



modis_df = pd.read_csv(modis_file)
modis_df.columns = modis_df.columns.str.strip()

modis_df = modis_df[
    [
        "year",
        "month",
        "region",
        "mean_LST_Day_C",
        "mean_LST_Night_C"
    ]
].copy()

modis_2024 = modis_df[modis_df["year"] == target_year].copy()



modis_pivot = modis_2024.pivot_table(
    index=["year", "month"],
    columns="region",
    values=["mean_LST_Day_C", "mean_LST_Night_C"],
    aggfunc="mean"
)

modis_pivot.columns = [
    f"{value}_{region}" for value, region in modis_pivot.columns
]

modis_pivot = modis_pivot.reset_index()



modis_pivot["Daytime LST (°C)"] = modis_pivot["mean_LST_Day_C_Urban"]
modis_pivot["Nighttime LST (°C)"] = modis_pivot["mean_LST_Night_C_Urban"]

modis_pivot["Daytime Reference LST (°C)"] = modis_pivot["mean_LST_Day_C_Reference_1km"]
modis_pivot["Nighttime Reference LST (°C)"] = modis_pivot["mean_LST_Night_C_Reference_1km"]

modis_pivot["Daytime SUHI (°C)"] = (
    modis_pivot["Daytime LST (°C)"] -
    modis_pivot["Daytime Reference LST (°C)"]
)

modis_pivot["Nighttime SUHI (°C)"] = (
    modis_pivot["Nighttime LST (°C)"] -
    modis_pivot["Nighttime Reference LST (°C)"]
)

suhi_2024 = modis_pivot[
    [
        "year",
        "month",
        "Daytime LST (°C)",
        "Daytime Reference LST (°C)",
        "Daytime SUHI (°C)",
        "Nighttime LST (°C)",
        "Nighttime Reference LST (°C)",
        "Nighttime SUHI (°C)"
    ]
].copy()

suhi_2024 = suhi_2024.rename(columns={
    "year": "Year",
    "month": "Month"
})

suhi_2024 = suhi_2024.round(2)

print("2024 MODIS LST and SUHI table:")
display(suhi_2024)



monthly_pollution_2024 = pd.read_csv(pollution_file)

monthly_pollution_2024["Year"] = monthly_pollution_2024["Year"].astype(int)
monthly_pollution_2024["Month"] = monthly_pollution_2024["Month"].astype(int)

print("\n2024 monthly pollution table:")
display(monthly_pollution_2024)



merged_2024 = pd.merge(
    suhi_2024,
    monthly_pollution_2024,
    on=["Year", "Month"],
    how="inner"
)

merged_2024 = merged_2024.round(2)

print("\nFINAL MERGED 2024 TABLE: LST + SUHI + POLLUTANTS")
display(merged_2024)

output_csv = base_path / "Merged_LST_SUHI_Pollution_2024.csv"
merged_2024.to_csv(output_csv, index=False)

print("\nSaved:", output_csv)


month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

merged_2024["Month_Name"] = merged_2024["Month"].map(month_names)


def plot_triple_scale_nighttime_2024(df, pollutant_1, pollutant_2, title, output_name):

    fig, ax1 = plt.subplots(figsize=(10, 5))


    ax1.plot(
        df["Month_Name"],
        df["Nighttime SUHI (°C)"],
        marker="o",
        linewidth=2,
        label="Nighttime SUHI"
    )

    ax1.set_xlabel("Month")
    ax1.set_ylabel("Nighttime SUHI (°C)")
    ax1.tick_params(axis="x", rotation=45)


    ax2 = ax1.twinx()

    ax2.plot(
        df["Month_Name"],
        df[pollutant_1],
        marker="s",
        linewidth=2,
        linestyle="--",
        label=pollutant_1
    )

    ax2.set_ylabel(pollutant_1)

    ax3 = ax1.twinx()

    ax3.spines["right"].set_position(("outward", 60))

    ax3.plot(
        df["Month_Name"],
        df[pollutant_2],
        marker="^",
        linewidth=2,
        linestyle=":",
        label=pollutant_2
    )

    ax3.set_ylabel(pollutant_2)

    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    lines_3, labels_3 = ax3.get_legend_handles_labels()

    ax1.legend(
        lines_1 + lines_2 + lines_3,
        labels_1 + labels_2 + labels_3,
        loc="upper left",
        fontsize=9
    )

    ax1.set_title(title)
    ax1.grid(True, alpha=0.3)

    plt.tight_layout()

    output_path = base_path / output_name
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

    print("Saved:", output_path)

# ------------------------------------------------------------
# 8. Plot 1: Nighttime SUHI with PM2.5 and PM10
# ------------------------------------------------------------

plot_triple_scale_nighttime_2024(
    df=merged_2024,
    pollutant_1="PM2.5 (µg/m³)",
    pollutant_2="PM10 (µg/m³)",
    title="Monthly Nighttime SUHI with PM2.5 and PM10 during 2024",
    output_name="Nighttime_SUHI_PM25_PM10_2024.png"
)

# ------------------------------------------------------------
# 9. Plot 2: Nighttime SUHI with NO2 and CO
# ------------------------------------------------------------

plot_triple_scale_nighttime_2024(
    df=merged_2024,
    pollutant_1="NO2 (µg/m³)",
    pollutant_2="CO (mg/m³)",
    title="Monthly Nighttime SUHI with NO2 and CO during 2024",
    output_name="Nighttime_SUHI_NO2_CO_2024.png"
)

# ------------------------------------------------------------
# 10. Plot 3: Nighttime SUHI with Ozone and SO2
# ------------------------------------------------------------

plot_triple_scale_nighttime_2024(
    df=merged_2024,
    pollutant_1="Ozone (µg/m³)",
    pollutant_2="SO2 (µg/m³)",
    title="Monthly Nighttime SUHI with Ozone and SO2 during 2024",
    output_name="Nighttime_SUHI_Ozone_SO2_2024.png"
)

import pandas as pd
from scipy.stats import pearsonr
from pathlib import Path
from IPython.display import display

# ============================================================
# 2024 SUHI vs POLLUTANTS CORRELATION
# Main focus: Nighttime SUHI
# Supporting: Daytime SUHI
# ============================================================

base_path = Path("/content")

merged_file = base_path / "Merged_LST_SUHI_Pollution_2024.csv"

df = pd.read_csv(merged_file)

pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

suhi_columns = [
    "Nighttime SUHI (°C)",
    "Daytime SUHI (°C)"
]

correlation_rows = []

for pollutant in pollutants:

    row = {
        "Pollutant": pollutant
    }

    for suhi_col in suhi_columns:

        temp = df[[suhi_col, pollutant]].dropna()

        if len(temp) >= 3:
            r_value, p_value = pearsonr(temp[suhi_col], temp[pollutant])
        else:
            r_value, p_value = None, None

        if suhi_col == "Nighttime SUHI (°C)":
            row["Nighttime SUHI r"] = r_value
            row["Nighttime SUHI p-value"] = p_value

        elif suhi_col == "Daytime SUHI (°C)":
            row["Daytime SUHI r"] = r_value
            row["Daytime SUHI p-value"] = p_value

    correlation_rows.append(row)

correlation_2024 = pd.DataFrame(correlation_rows)

correlation_2024 = correlation_2024[
    [
        "Pollutant",
        "Nighttime SUHI r",
        "Nighttime SUHI p-value",
        "Daytime SUHI r",
        "Daytime SUHI p-value"
    ]
]

correlation_2024 = correlation_2024.round(3)

print("2024 SUHI vs pollutant correlation table")
display(correlation_2024)


output_file = base_path / "SUHI_Pollutant_Correlation_2024.csv"
correlation_2024.to_csv(output_file, index=False)

print("\nSaved:", output_file)

import pandas as pd
from scipy.stats import pearsonr
from pathlib import Path
from IPython.display import display

# ============================================================
# POLLUTANT-TO-POLLUTANT CORRELATION ANALYSIS
# Years: 2023 and 2024
# Based on monthly average pollution values
# ============================================================

base_path = Path("/content")

pollutants = [
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

def pollutant_correlation_analysis(year):

    merged_file = base_path / f"Merged_LST_SUHI_Pollution_{year}.csv"

    if not merged_file.exists():
        raise FileNotFoundError(f"File not found: {merged_file}")

    df = pd.read_csv(merged_file)

    pollutant_df = df[pollutants].copy()



    r_matrix = pollutant_df.corr(method="pearson").round(3)



    p_matrix = pd.DataFrame(
        index=pollutants,
        columns=pollutants
    )

    for pollutant_1 in pollutants:
        for pollutant_2 in pollutants:

            temp = df[[pollutant_1, pollutant_2]].dropna()

            if pollutant_1 == pollutant_2:
                p_matrix.loc[pollutant_1, pollutant_2] = 0.000

            elif len(temp) >= 3:
                r_value, p_value = pearsonr(
                    temp[pollutant_1],
                    temp[pollutant_2]
                )
                p_matrix.loc[pollutant_1, pollutant_2] = round(p_value, 3)

            else:
                p_matrix.loc[pollutant_1, pollutant_2] = None


    print("=" * 100)
    print(f"{year} POLLUTANT-TO-POLLUTANT PEARSON r-VALUE MATRIX")
    display(r_matrix)

    print("=" * 100)
    print(f"{year} POLLUTANT-TO-POLLUTANT p-VALUE MATRIX")
    display(p_matrix)



    r_output = base_path / f"Pollutant_Correlation_r_Matrix_{year}.csv"
    p_output = base_path / f"Pollutant_Correlation_p_Matrix_{year}.csv"

    r_matrix.to_csv(r_output)
    p_matrix.to_csv(p_output)

    print("\nSaved:")
    print(r_output)
    print(p_output)

    return r_matrix, p_matrix


# r value matrix be used for correlation

r_2023, p_2023 = pollutant_correlation_analysis(2023)

r_2024, p_2024 = pollutant_correlation_analysis(2024)

base_path = Path("/content")
uhi_study_path = Path("/content/drive/MyDrive/UHI_study")
classic_path = Path("/content/drive/MyDrive/Classic UHI")

target_year = 2023



station_lst_file = uhi_study_path / "NDVI_LST_2023_station_buffers_monthly.csv"
reference_file = classic_path / "Classic_UHI_LST_NDVI_1km_Reference_2020_2024.csv"
pollution_file = base_path / "Stationwise_Monthly_Pollution_2023.csv"



station_lst = pd.read_csv(station_lst_file)
station_lst.columns = station_lst.columns.str.strip()

station_lst = station_lst[
    [
        "year",
        "month",
        "station_name",
        "group",
        "station_type",
        "LST_C",
        "NDVI"
    ]
].copy()

station_lst = station_lst[station_lst["year"] == target_year].copy()

station_lst = station_lst.rename(columns={
    "year": "Year",
    "month": "Month",
    "station_name": "Station",
    "group": "Group",
    "station_type": "Station Type",
    "LST_C": "Station LST (°C)"
})

station_lst["Month"] = station_lst["Month"].astype(int)



reference_df = pd.read_csv(reference_file)
reference_df.columns = reference_df.columns.str.strip()

print("Reference file columns:")
print(list(reference_df.columns))

reference_2023 = reference_df[reference_df["year"] == target_year].copy()



if "region" in reference_2023.columns:
    reference_2023 = reference_2023[
        reference_2023["region"].astype(str).str.lower().str.contains("reference")
    ].copy()


possible_ref_lst_cols = [
    "mean_LST_C",
    "mean_LST",
    "LST_C",
    "Reference_1km_LST_C",
    "reference_LST_C"
]

ref_lst_col = None
for col in possible_ref_lst_cols:
    if col in reference_2023.columns:
        ref_lst_col = col
        break

if ref_lst_col is None:
    raise ValueError(
        "Could not detect reference LST column. Check printed reference file columns above."
    )

reference_2023 = reference_2023[["year", "month", ref_lst_col]].copy()

reference_2023 = reference_2023.rename(columns={
    "year": "Year",
    "month": "Month",
    ref_lst_col: "Reference 1km LST (°C)"
})

reference_2023["Month"] = reference_2023["Month"].astype(int)



station_uhi = pd.merge(
    station_lst,
    reference_2023,
    on=["Year", "Month"],
    how="left"
)

station_uhi["Station UHI (°C)"] = (
    station_uhi["Station LST (°C)"] -
    station_uhi["Reference 1km LST (°C)"]
)



station_pollution = pd.read_csv(pollution_file)
station_pollution.columns = station_pollution.columns.str.strip()

station_pollution = station_pollution.rename(columns={
    "Station": "Station",
    "Month": "Month"
})

station_pollution["Month"] = station_pollution["Month"].astype(int)



def clean_station_name(name):
    name = str(name).strip().lower()
    name = name.replace(",", "")
    name = name.replace("-", " ")
    name = " ".join(name.split())
    return name

station_uhi["Station_clean"] = station_uhi["Station"].apply(clean_station_name)
station_pollution["Station_clean"] = station_pollution["Station"].apply(clean_station_name)



station_monthly_final_2023 = pd.merge(
    station_uhi,
    station_pollution,
    on=["Station_clean", "Month"],
    how="left",
    suffixes=("", "_pollution")
)

# Use clean station name from LST file
station_monthly_final_2023["Station"] = station_monthly_final_2023["Station"]



final_columns = [
    "Year",
    "Month",
    "Station",
    "Group",
    "Station Type",
    "Station LST (°C)",
    "Reference 1km LST (°C)",
    "Station UHI (°C)",
    "NDVI",
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

station_monthly_final_2023 = station_monthly_final_2023[final_columns].copy()

station_monthly_final_2023 = station_monthly_final_2023.round(2)


month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

station_monthly_final_2023.insert(
    2,
    "Month Name",
    station_monthly_final_2023["Month"].map(month_names)
)



print("=" * 100)
print("COMBINED STATION-WISE MONTHLY UHI + POLLUTION TABLE, 2023")
display(station_monthly_final_2023)

combined_output = base_path / "Stationwise_UHI_Pollution_2023_AllStations.csv"
station_monthly_final_2023.to_csv(combined_output, index=False)

print("\nSaved combined file:")
print(combined_output)



output_folder = base_path / "Stationwise_UHI_Pollution_2023_Tables"
output_folder.mkdir(exist_ok=True)

print("\n" + "=" * 100)
print("INDIVIDUAL STATION TABLES")

for station in sorted(station_monthly_final_2023["Station"].dropna().unique()):

    station_table = station_monthly_final_2023[
        station_monthly_final_2023["Station"] == station
    ].copy()

    station_table = station_table.sort_values("Month")

    print("\n" + "=" * 100)
    print(station)
    display(station_table)

    safe_name = (
        station.replace(",", "")
        .replace("/", "_")
        .replace(" ", "_")
    )

    output_file = output_folder / f"{safe_name}_UHI_Pollution_2023.csv"
    station_table.to_csv(output_file, index=False)

print("\nSaved individual station tables in:")
print(output_folder)

base_path = Path("/content")
classic_path = Path("/content/drive/MyDrive/Classic UHI")

target_year = 2023


station_modis_file = classic_path / "MODIS_Day_Night_LST_2023_station_buffers_monthly.csv"
reference_modis_file = classic_path / "MODIS_Day_Night_LST_1km_Reference_2020_2024.csv"
pollution_file = base_path / "Stationwise_Monthly_Pollution_2023.csv"


station_modis = pd.read_csv(station_modis_file)
station_modis.columns = station_modis.columns.str.strip()

print("Station MODIS columns:")
print(list(station_modis.columns))

station_modis = station_modis[
    [
        "year",
        "month",
        "station_name",
        "group",
        "station_type",
        "mean_LST_Day_C",
        "mean_LST_Night_C"
    ]
].copy()

station_modis = station_modis[station_modis["year"] == target_year].copy()

station_modis = station_modis.rename(columns={
    "year": "Year",
    "month": "Month",
    "station_name": "Station",
    "group": "Group",
    "station_type": "Station Type",
    "mean_LST_Day_C": "Station Day LST (°C)",
    "mean_LST_Night_C": "Station Night LST (°C)"
})

station_modis["Month"] = station_modis["Month"].astype(int)



reference_modis = pd.read_csv(reference_modis_file)
reference_modis.columns = reference_modis.columns.str.strip()

print("\nReference MODIS columns:")
print(list(reference_modis.columns))

reference_2023 = reference_modis[
    (reference_modis["year"] == target_year) &
    (reference_modis["region"].astype(str).str.lower().str.contains("reference"))
].copy()

reference_2023 = reference_2023[
    [
        "year",
        "month",
        "mean_LST_Day_C",
        "mean_LST_Night_C"
    ]
].copy()

reference_2023 = reference_2023.rename(columns={
    "year": "Year",
    "month": "Month",
    "mean_LST_Day_C": "Reference Day LST (°C)",
    "mean_LST_Night_C": "Reference Night LST (°C)"
})

reference_2023["Month"] = reference_2023["Month"].astype(int)



station_uhi = pd.merge(
    station_modis,
    reference_2023,
    on=["Year", "Month"],
    how="left"
)

station_uhi["Daytime Station UHI (°C)"] = (
    station_uhi["Station Day LST (°C)"] -
    station_uhi["Reference Day LST (°C)"]
)

station_uhi["Nighttime Station UHI (°C)"] = (
    station_uhi["Station Night LST (°C)"] -
    station_uhi["Reference Night LST (°C)"]
)


station_pollution = pd.read_csv(pollution_file)
station_pollution.columns = station_pollution.columns.str.strip()

station_pollution["Month"] = station_pollution["Month"].astype(int)



def clean_station_name(name):
    name = str(name).strip().lower()
    name = name.replace(",", "")
    name = name.replace("-", " ")
    name = " ".join(name.split())
    return name

station_uhi["Station_clean"] = station_uhi["Station"].apply(clean_station_name)
station_pollution["Station_clean"] = station_pollution["Station"].apply(clean_station_name)



station_monthly_modis_2023 = pd.merge(
    station_uhi,
    station_pollution,
    on=["Station_clean", "Month"],
    how="left",
    suffixes=("", "_pollution")
)



final_columns = [
    "Year",
    "Month",
    "Station",
    "Group",
    "Station Type",
    "Station Day LST (°C)",
    "Reference Day LST (°C)",
    "Daytime Station UHI (°C)",
    "Station Night LST (°C)",
    "Reference Night LST (°C)",
    "Nighttime Station UHI (°C)",
    "CO (mg/m³)",
    "NO2 (µg/m³)",
    "Ozone (µg/m³)",
    "PM2.5 (µg/m³)",
    "PM10 (µg/m³)",
    "SO2 (µg/m³)"
]

station_monthly_modis_2023 = station_monthly_modis_2023[final_columns].copy()
station_monthly_modis_2023 = station_monthly_modis_2023.round(2)


month_names = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr",
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug",
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

station_monthly_modis_2023.insert(
    2,
    "Month Name",
    station_monthly_modis_2023["Month"].map(month_names)
)



print("=" * 100)
print("COMBINED MODIS STATION-WISE DAY/NIGHT UHI + POLLUTION TABLE, 2023")
display(station_monthly_modis_2023)

combined_output = base_path / "MODIS_Stationwise_Day_Night_UHI_Pollution_2023_AllStations.csv"
station_monthly_modis_2023.to_csv(combined_output, index=False)

print("\nSaved combined file:")
print(combined_output)

# ------------------------------------------------------------
# Display and save 13 individual station tables
# ------------------------------------------------------------

output_folder = base_path / "MODIS_Stationwise_Day_Night_UHI_Pollution_2023_Tables"
output_folder.mkdir(exist_ok=True)

print("\n" + "=" * 100)
print("INDIVIDUAL STATION TABLES")

for station in sorted(station_monthly_modis_2023["Station"].dropna().unique()):

    station_table = station_monthly_modis_2023[
        station_monthly_modis_2023["Station"] == station
    ].copy()

    station_table = station_table.sort_values("Month")

    print("\n" + "=" * 100)
    print(station)
    display(station_table)

    safe_name = (
        station.replace(",", "")
        .replace("/", "_")
        .replace(" ", "_")
    )

    output_file = output_folder / f"{safe_name}_MODIS_Day_Night_UHI_Pollution_2023.csv"
    station_table.to_csv(output_file, index=False)

print("\nSaved individual station tables in:")
print(output_folder)